### PR TITLE
Add posibility to deploy OSDs

### PR DESCRIPTION
**Pull request by stamak**
Just add pillars:

ceph:
  osds:
    active:
      - /dev/sdc
      - /dev/sdd

And run command:
  salt your-host state.sls ceph.osd

### CODE REVIEW

**Comment by stamak** [comment]
@aboe76  @babilen pls review?
thx

**Comment by aboe76** [comment]
@stamak, will you be updating this later with remove osd? 

could you expand the example that {{ osd_device }}, could also be used for other options to include:
like --zap-disk or --fs-type...?

**Comment by stamak** [comment]
@aboe76 yes I will add removing OSD and options in next patch

**Comment by aboe76** [comment]
@stamak perfect,

**Comment by iggy** [comment]
It would be awesome if future versions also supported setting journal devices.

**Pull request merged**
