### PR TITLE
Add possibility to configure config file

### PR DESCRIPTION
**Pull request by stamak**
- Add possibility to configure global section
- Set default authentication type to _cephx_

### CODE REVIEW

**Comment by stamak** [comment]
@babilen , @aboe76 could you review it ?

**Comment by aboe76** [comment]
@stamak will do tomorrow

**Comment by aboe76** [comment]
@stamak 
could you make the sections also dynamic?

So we can add more sections like 
[global]
[osd]
[mon]
[ods]
[mds]
[client]

see:
http://docs.ceph.com/docs/jewel/rados/configuration/ceph-conf/

**Comment by stamak** [comment]
@aboe76  I am going to do this in next state files for corresponding component
for example monitor will configure mon section

now init.sls configure global - this enough for ceph clients to connect to ceph cluster

**Comment by aboe76** [comment]
ok perfect

**Pull request merged**
